sudo: required
services:
  - docker

before_install:
  - docker build -t gb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-975050078620"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"